### PR TITLE
WIP: use const ref in boost::fusion::vector, fix #511

### LINKED ISSUE #511: Const correctness in boost::fusion::vector for ArgsType & Boost versions
Hi,

If we consider this simple exemple:
```
#include <boost/fusion/container/vector.hpp>

struct Base
{
    typedef boost::fusion::vector<const unsigned long, int> ArgsType;
    ArgsType args;

    Base(ArgsType args): args(args) {};
};

int main()
{
    Base::ArgsType args(3, 4);
    Base instance(args);
    return 0;
}
```

It compiles on Boost 1.64, 1.65, doesn't n 1.66 & 1.67, and compiles again in 1.68, as you can see here: https://godbolt.org/z/aHrEBe

When it doesn't, the issue is with the `const` keyword:
```
/opt/compiler-explorer/libs/boost_1_67_0/boost/fusion/container/vector/detail/deref_impl.hpp:47:49: error: binding reference of type 'boost::fusion::extension::deref_impl<boost::fusion::vector_iterator_tag>::apply<boost::fusion::vector_iterator<boost::fusion::vector<const long unsigned int, int>, 0> >::type' {aka 'long unsigned int&'} to 'const long unsigned int' discards qualifiers
```

I will dig a bit, but I think this is an issue in Boost, so I suggest to simply avoid those versions.

### PR DESCRIPTION
**Pull request by nim65s**
This follows #575 

This is a work in progress, as for now unittest/joint-configurations is not passing:

```
joint-configurations: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:396: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
```

### CODE REVIEW

**Comment by jcarpent** [comment]
I do not have this issue on my configuration. Can you run GDB on it?

**Comment by nim65s** [comment]
I have been playing with GDB a bit, and added this patch:
```
--- src/multibody/liegroup/liegroup-algo.hxx
+++ src/multibody/liegroup/liegroup-algo.hxx
@@ -262,7 +262,7 @@ namespace pinocchio
   {
     template<typename ConfigVectorIn1, typename ConfigVectorIn2, typename DistanceVectorOut>
     static void run(const JointModelBase<JointModel> & jmodel,
-                    const JointIndex i,
+                    const JointIndex & i,
                     const Eigen::MatrixBase<ConfigVectorIn1> & q0,
                     const Eigen::MatrixBase<ConfigVectorIn2> & q1,
                     const Eigen::MatrixBase<DistanceVectorOut> & distances)

```
without success for now. I can reproduce that at least on 16.04 & fedora 28.
The bug is clearly that at some point, `i` gets the address of the `JointIndex` instead of its value,  so I must be missing another `const JointIndex i` somewhere

**Comment by nim65s** [comment]
Ok, I think I got it, thanks :)

**Comment by jcarpent** [comment]
@nim65s Have you tried using pointers instead of references?

**Comment by nim65s** [comment]
I have tried, but without any success so far.

**Comment by jcarpent** [comment]
I'm working on this issue right now. 
I will close this PR and suggest a new one soon.
